# **Bioinformatics Project - Computational Drug Discovery [Part 1] Download Bioactivity Data (Concised version)**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 1**, we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

Note for this Concised Version:
* Redundant code cells were deleted.
* Code cells for saving files to Google Drive has been deleted.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (0.10.9)
Requirement already satisfied: urllib3 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from chembl_webresource_client) (2.6.3)
Requirement already satisfied: requests>=2.18.4 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from chembl_webresource_client) (2.32.5)
Requirement already satisfied: requests-cache~=1.2 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from chembl_webresource_client) (1.3.1)
Requirement already satisfied: easydict in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.4)
Requirement already satisfied: url-normalize>=2.0 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: exceptiongroup>=1.1.1 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (1.3.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/students/mcubi/.conda/envs/bioinfo/lib/python3.10/site-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)

## **Importing libraries**

In [3]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for Acetylcholinesterase**

In [4]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('acetylcholinesterase')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Drosophila melanogaster,Acetylcholinesterase,18.0,False,CHEMBL2242744,"[{'accession': 'P07140', 'component_descriptio...",SINGLE PROTEIN,7227
1,[],Homo sapiens,Acetylcholinesterase,16.0,False,CHEMBL220,"[{'accession': 'P22303', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Torpedo californica,Acetylcholinesterase,16.0,False,CHEMBL4780,"[{'accession': 'P04058', 'component_descriptio...",SINGLE PROTEIN,7787
3,[],Mus musculus,Acetylcholinesterase,16.0,False,CHEMBL3198,"[{'accession': 'P21836', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Rattus norvegicus,Acetylcholinesterase,16.0,False,CHEMBL3199,"[{'accession': 'P37136', 'component_descriptio...",SINGLE PROTEIN,10116
5,[],Electrophorus electricus,Acetylcholinesterase,16.0,False,CHEMBL4078,"[{'accession': 'O42275', 'component_descriptio...",SINGLE PROTEIN,8005
6,[],Bos taurus,Acetylcholinesterase,16.0,False,CHEMBL4768,"[{'accession': 'P23795', 'component_descriptio...",SINGLE PROTEIN,9913
7,[],Anopheles gambiae,Acetylcholinesterase,16.0,False,CHEMBL2046266,"[{'accession': 'Q869C3', 'component_descriptio...",SINGLE PROTEIN,7165
8,[],Bemisia tabaci,AChE2,16.0,False,CHEMBL2366409,"[{'accession': 'B3SST5', 'component_descriptio...",SINGLE PROTEIN,7038
9,[],Leptinotarsa decemlineata,Acetylcholinesterase,16.0,False,CHEMBL2366490,"[{'accession': 'Q27677', 'component_descriptio...",SINGLE PROTEIN,7539
10,[],Nephotettix cincticeps,Ace-orthologous acetylcholinesterase,16.0,False,CHEMBL2366514,"[{'accession': 'Q9NJH6', 'component_descriptio...",SINGLE PROTEIN,94400
11,[],Gallus gallus,Acetylcholinesterase,16.0,False,CHEMBL3227914,"[{'accession': 'P36196', 'component_descriptio...",SINGLE PROTEIN,9031
12,[],Danio rerio,Acetylcholinesterase,16.0,False,CHEMBL3308995,"[{'accession': 'Q9DDE3', 'component_descriptio...",SINGLE PROTEIN,7955
13,[],Aedes aegypti,Acetylcholinesterase,16.0,False,CHEMBL4295607,"[{'accession': 'Q6A2E2', 'component_descriptio...",SINGLE PROTEIN,7159
14,[],Homo sapiens,Protein CutA,16.0,False,CHEMBL6067022,"[{'accession': 'O60888', 'component_descriptio...",SINGLE PROTEIN,9606
15,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL5752,"[{'accession': 'Q95P20', 'component_descriptio...",SINGLE PROTEIN,7370
16,[],Plutella xylostella,Acetylcholinesterase,15.0,False,CHEMBL2242729,"[{'accession': 'Q8MZM0', 'component_descriptio...",SINGLE PROTEIN,51655
17,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL2242743,"[{'accession': 'Q7YWJ9', 'component_descriptio...",SINGLE PROTEIN,7370
18,[],Pediculus humanus capitis,Acetylcholinesterase,15.0,False,CHEMBL2362988,"[{'accession': 'A2PZ98', 'component_descriptio...",SINGLE PROTEIN,121226
19,[],Spodoptera litura,Acetylcholinesterase,15.0,False,CHEMBL2366422,"[{'accession': 'C5IU80', 'component_descriptio...",SINGLE PROTEIN,69820
20,[],Laodelphax striatella,Acetylcholinesterase,15.0,False,CHEMBL2366446,"[{'accession': 'K4JQ36', 'component_descriptio...",SINGLE PROTEIN,195883
21,[],Schizaphis graminum,Acetylcholinesterase,15.0,False,CHEMBL2366511,"[{'accession': 'Q9BMJ1', 'component_descriptio...",SINGLE PROTEIN,13262
22,[],Homo sapiens,Cholinesterases; ACHE & BCHE,14.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606
23,[],Rattus norvegicus,Acetylcholinesterase and butyrylcholinesterase...,14.0,False,CHEMBL2111475,"[{'accession': 'P37136', 'component_descriptio...",SELECTIVITY GROUP,10116
24,[],Caenorhabditis elegans,Acetylcholinesterase 1,14.0,False,CHEMBL3341583,"[{'accession': 'P38433', 'component_descriptio...",SINGLE PROTEIN,6239
25,[],Equus caballus,Butyrylcholinesterase,11.0,False,CHEMBL5077,"[{'accession': 'Q9N1N9', 'component_descriptio...",SINGLE PROTEIN,9796
26,[],Equus caballus,Cholinesterase,11.0,False,CHEMBL5763,"[{'accession': 'P81908', 'component_descriptio...",SINGLE PROTEIN,9796
27,[],Canis lupus familiaris,Cholinesterase,11.0,False,CHEMBL4630814,"[{'accession': 'P32750', 'component_descriptio...",SINGLE PROTEIN,9615
28,[],Mus musculus,Cholinesterase,10.0,False,CHEMBL2528,"[{'accession': 'Q03311', 'component_descriptio...",SINGLE PROTEIN,10090
29,[],Rattus norvegicus,Butyrylcholinesterase,10.0,False,CHEMBL3403,"[{'accession': 'Q9JKC1', 'component_descriptio...",SINGLE PROTEIN,10116
30,[],Homo sapiens,Cholinesterase,5.0,False,CHEMBL1914,"[{'accession': 'P06276', 'component_descriptio...",SINGLE PROTEIN,9606

### **Select and retrieve bioactivity data for *Human Acetylcholinesterase* (first entry)**

We will assign the fifth entry (which corresponds to the target protein, *Human Acetylcholinesterase*) to the ***selected_target*** variable

In [5]:
selected_target = targets.target_chembl_id[4]
selected_target

'CHEMBL3199'

Here, we will retrieve only bioactivity data for *Human Acetylcholinesterase* (CHEMBL220) that are reported as pChEMBL values.

In [6]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [7]:
df = pd.DataFrame.from_dict(res)

In [9]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32049,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.1
1,None,None,32050,[],CHEMBL642842,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.17
2,None,None,34486,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.2
3,None,None,34487,[],CHEMBL642842,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.2
4,None,None,38116,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983030,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,0.153
1916,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983031,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,1.53
1917,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983032,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,3.231
1918,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25500533,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5332046,Inhibition of rat cortex homogenate AChE prein...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,1.2
1919,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25527622,[],CHEMBL5339559,Inhibition of rat cortex homogenate AChE by El...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,0.41

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [10]:
df.to_csv('acetylcholinesterase_01_bioactivity_data_raw.csv', index=False)

## **Handling missing data**
If any compounds has missing value for the **standard_value** and **canonical_smiles** column then drop it.

In [11]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_2213623/3852201246.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32049,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.1
1,None,None,32050,[],CHEMBL642842,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.17
2,None,None,34486,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.2
3,None,None,34487,[],CHEMBL642842,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.2
4,None,None,38116,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983030,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,0.153
1916,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983031,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,1.53
1917,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983032,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,3.231
1918,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25500533,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5332046,Inhibition of rat cortex homogenate AChE prein...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,1.2
1919,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25527622,[],CHEMBL5339559,Inhibition of rat cortex homogenate AChE by El...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,0.41

In [12]:
len(df2.canonical_smiles.unique())

1571

In [13]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32049,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.1
2,None,None,34486,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.2
4,None,None,38116,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.26
6,None,None,41591,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.06
8,None,None,42915,[],CHEMBL642843,Effect on Acetylcholinesterase activity in rat...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,I50,mM,UO_0000065,None,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1912,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24963337,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5216421,Inhibition of Sprague-Dawley rat cortex AChE u...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,6.97
1913,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24963338,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5216421,Inhibition of Sprague-Dawley rat cortex AChE u...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,4.11
1916,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983031,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,1.53
1917,"{'action_type': 'INHIBITOR', 'description': 'N...",None,24983032,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5226654,Inhibition of rat cortex AChE using acetylthio...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,3.231
1919,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25527622,[],CHEMBL5339559,Inhibition of rat cortex homogenate AChE by El...,B,None,None,BAO_0000190,...,Rattus norvegicus,Acetylcholinesterase,10116,None,None,IC50,uM,UO_0000065,None,0.41

## **Data pre-processing of the bioactivity data**

### **Combine the 3 columns (molecule_chembl_id,canonical_smiles,standard_value) and bioactivity_class into a DataFrame**

In [14]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL15886,CC[N+](C)(CC)CC(=O)CCN1C(=O)CCC1=O.[I-],100000.0
2,CHEMBL556129,C[n+]1ccccc1CCC(O)CCl.[I-],200000.0
4,CHEMBL15795,C[N+](C)(C)CCCCl.[Br-],260000.0
6,CHEMBL276539,BrCCCCCC[n+]1ccccc1.[Br-],60000.0
8,CHEMBL278956,CC[N+](C)(CC)CCc1ccncc1.[I-],200000.0
...,...,...,...
1912,CHEMBL5219903,CN1CCN(C(=O)Oc2ccc(/C=C/c3cc(OC(=O)N4CCN(C)CC4...,6970.0
1913,CHEMBL5220947,O=C(Oc1ccc(/C=C/c2cc(OC(=O)N3CCN(Cc4ccccc4)CC3...,4110.0
1916,CHEMBL5271210,O=C1[C@@H]2Cc3c([nH]c4ccccc34)[C@@H](c3ccc4c(c...,1530.0
1917,CHEMBL5275356,COc1ccc([C@@H]2c3[nH]c4ccccc4c3C[C@H]3C(=O)N(C...,3231.0
1919,CHEMBL5422194,CCN(CCCCCCOc1ccc(/C=C/C(=O)c2c(O)cc(OC)c(O)c2O...,410.0

Saves dataframe to CSV file

In [15]:
df3.to_csv('acetylcholinesterase_02_bioactivity_data_preprocessed.csv', index=False)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [16]:
df4 = pd.read_csv('acetylcholinesterase_02_bioactivity_data_preprocessed.csv')

In [17]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

In [18]:
bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL15886,CC[N+](C)(CC)CC(=O)CCN1C(=O)CCC1=O.[I-],100000.0,inactive
1,CHEMBL556129,C[n+]1ccccc1CCC(O)CCl.[I-],200000.0,inactive
2,CHEMBL15795,C[N+](C)(C)CCCCl.[Br-],260000.0,inactive
3,CHEMBL276539,BrCCCCCC[n+]1ccccc1.[Br-],60000.0,inactive
4,CHEMBL278956,CC[N+](C)(CC)CCc1ccncc1.[I-],200000.0,inactive
...,...,...,...,...
1566,CHEMBL5219903,CN1CCN(C(=O)Oc2ccc(/C=C/c3cc(OC(=O)N4CCN(C)CC4...,6970.0,intermediate
1567,CHEMBL5220947,O=C(Oc1ccc(/C=C/c2cc(OC(=O)N3CCN(Cc4ccccc4)CC3...,4110.0,intermediate
1568,CHEMBL5271210,O=C1[C@@H]2Cc3c([nH]c4ccccc34)[C@@H](c3ccc4c(c...,1530.0,intermediate
1569,CHEMBL5275356,COc1ccc([C@@H]2c3[nH]c4ccccc4c3C[C@H]3C(=O)N(C...,3231.0,intermediate
1570,CHEMBL5422194,CCN(CCCCCCOc1ccc(/C=C/C(=O)c2c(O)cc(OC)c(O)c2O...,410.0,active

Saves dataframe to CSV file

In [19]:
df5.to_csv('acetylcholinesterase_03_bioactivity_data_curated.csv', index=False)

In [24]:
! zip acetylcholinesterase.zip acetylcholinesterase_0[1-3]*.csv

  adding: acetylcholinesterase_01_bioactivity_data_raw.csv (deflated 91%)
  adding: acetylcholinesterase_02_bioactivity_data_preprocessed.csv (deflated 82%)
  adding: acetylcholinesterase_03_bioactivity_data_curated.csv (deflated 83%)

In [25]:
! ls -l

total 17780
-rw-r--r-- 1 mcubi students 1013813 Mar 23 18:29 acetylcholinesterase_01_bioactivity_data_raw.csv
-rw-r--r-- 1 mcubi students  113254 Mar 23 18:29 acetylcholinesterase_02_bioactivity_data_preprocessed.csv
-rw-r--r-- 1 mcubi students  127407 Mar 23 18:29 acetylcholinesterase_03_bioactivity_data_curated.csv
-rw-r--r-- 1 mcubi students  655414 Mar 23 18:14 acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv
-rw-r--r-- 1 mcubi students  489152 Mar 23 18:14 acetylcholinesterase_05_bioactivity_data_2class_pIC50.csv
-rw-r--r-- 1 mcubi students 8363909 Mar 23 18:14 acetylcholinesterase_06_bioactivity_data_3class_pIC50_pubchem_fp.csv
-rw-r--r-- 1 mcubi students 6323895 Mar 23 18:14 acetylcholinesterase_07_bioactivity_data_2class_pIC50_pubchem_fp.csv
-rw-r--r-- 1 mcubi students  134859 Mar 23 18:32 acetylcholinesterase.zip
-rw-r--r-- 1 mcubi students  104677 Mar 23 18:30 CDD_ML_Part_1_Acetylcholinesterase_Bioactivity_Data_Concised.ipynb
-rw-r--r-- 1 mcubi students  313244 Mar 23 18:14 CDD_ML_Part_2_Acetylcholinesterase_Exploratory_Data_Analysis.ipynb
-rw-r--r-- 1 mcubi students  208719 Mar 23 18:14 CDD_ML_Part_3_Acetylcholinesterase_Descriptor_Dataset_Preparation.ipynb
-rw-r--r-- 1 mcubi students  100076 Mar 23 18:14 CDD_ML_Part_4_Acetylcholinesterase_Regression_Random_Forest.ipynb
-rw-r--r-- 1 mcubi students  230778 Mar 23 18:14 CDD_ML_Part_5_Acetylcholinesterase_Compare_Regressors.ipynb
-rw-r--r-- 1 mcubi students      29 Mar 23 18:14 README.md

---