# **Bioinformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 3**, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

---

## **Download PaDEL-Descriptor**

In [1]:
# These files were deleted a few months ago, so I loaded the repository from an earlier
# version before the files were deleted and downloaded them myself, placing them in
# my verison of the bioinformatics tutorial repository

# ! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
# ! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh

In [2]:
! unzip padel.zip

Archive:  padel.zip
   creating: PaDEL-Descriptor/
  inflating: __MACOSX/._PaDEL-Descriptor
  inflating: PaDEL-Descriptor/MACCSFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._MACCSFingerprinter.xml
  inflating: PaDEL-Descriptor/AtomPairs2DFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._AtomPairs2DFingerprinter.xml
  inflating: PaDEL-Descriptor/EStateFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._EStateFingerprinter.xml
  inflating: PaDEL-Descriptor/Fingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._Fingerprinter.xml
  inflating: PaDEL-Descriptor/.DS_Store
  inflating: __MACOSX/PaDEL-Descriptor/._.DS_Store
   creating: PaDEL-Descriptor/license/
  inflating: __MACOSX/PaDEL-Descriptor/._license
  inflating: PaDEL-Descriptor/KlekotaRothFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._KlekotaRothFingerprintCount.xml
  inflating: PaDEL-Descriptor/config
  inflating: __MACOSX/PaDEL-Descriptor/._config
  inflating: PaDEL-Descriptor/PubchemFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._PubchemFingerprinter.xml
  inflating: PaDEL-Descriptor/ExtendedFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._ExtendedFingerprinter.xml
  inflating: PaDEL-Descriptor/KlekotaRothFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._KlekotaRothFingerprinter.xml
  inflating: PaDEL-Descriptor/GraphOnlyFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._GraphOnlyFingerprinter.xml
  inflating: PaDEL-Descriptor/SubstructureFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._SubstructureFingerprinter.xml
  inflating: PaDEL-Descriptor/Descriptors.xls
  inflating: __MACOSX/PaDEL-Descriptor/._Descriptors.xls
   creating: PaDEL-Descriptor/lib/
  inflating: __MACOSX/PaDEL-Descriptor/._lib
  inflating: PaDEL-Descriptor/PaDEL-Descriptor.jar
  inflating: __MACOSX/PaDEL-Descriptor/._PaDEL-Descriptor.jar
  inflating: PaDEL-Descriptor/SubstructureFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._SubstructureFingerprintCount.xml
  inflating: PaDEL-Descriptor/AtomPairs2DFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._AtomPairs2DFingerprintCount.xml
  inflating: PaDEL-Descriptor/descriptors.xml
  inflating: __MACOSX/PaDEL-Descriptor/._descriptors.xml
  inflating: PaDEL-Descriptor/license/lgpl-2.1.txt
  inflating: __MACOSX/PaDEL-Descriptor/license/._lgpl-2.1.txt
  inflating: PaDEL-Descriptor/license/LICENSE.txt
  inflating: __MACOSX/PaDEL-Descriptor/license/._LICENSE.txt
  inflating: PaDEL-Descriptor/license/README - CDK
  inflating: __MACOSX/PaDEL-Descriptor/license/._README - CDK
  inflating: PaDEL-Descriptor/license/lgpl.license
  inflating: __MACOSX/PaDEL-Descriptor/license/._lgpl.license
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(3).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(6).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL.jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(4).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(2).jar
  inflating: PaDEL-Descriptor/lib/xom-1.1(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._xom-1.1(1).jar
  inflating: PaDEL-Descriptor/lib/swing-worker-1.1.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._swing-worker-1.1.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(3).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(5).jar
  inflating: PaDEL-Descriptor/lib/jama(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(1).jar
  inflating: PaDEL-Descriptor/lib/appframework-1.0.3.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._appframework-1.0.3.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(7).jar
  inflating: PaDEL-Descriptor/lib/vecmath1.2-1.14.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._vecmath1.2-1.14.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(6).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(2).jar
  inflating: PaDEL-Descriptor/lib/jama(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(6).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(2).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(3).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(4).jar
  inflating: PaDEL-Descriptor/lib/ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(1).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(8).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(8).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(1).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs.jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(4).jar
  inflating: PaDEL-Descriptor/lib/xom-1.1.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._xom-1.1.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(5).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(2).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(3).jar
  inflating: PaDEL-Descriptor/lib/jama(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(7).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(6).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(1).jar
  inflating: PaDEL-Descriptor/lib/jama(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(4).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(2).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(3).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(2).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(3).jar
  inflating: PaDEL-Descriptor/lib/l2fprod-common-all(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._l2fprod-common-all(1).jar
  inflating: PaDEL-Descriptor/lib/jama.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama.jar
  inflating: PaDEL-Descriptor/lib/l2fprod-common-all.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._l2fprod-common-all.jar
  inflating: PaDEL-Descriptor/lib/jama(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(5).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(1).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(7).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(4).jar
  inflating: PaDEL-Descriptor/lib/cdk-1.4.15.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._cdk-1.4.15.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(5).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(1).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(8).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(8).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(6).jar
  inflating: PaDEL-Descriptor/lib/jama(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(2).jar
  inflating: PaDEL-Descriptor/lib/jama(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(3).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(1).jar
  inflating: PaDEL-Descriptor/lib/guava-17.0.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._guava-17.0.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(4).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(5).jar

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [3]:
# Don't need this since we have our own version of the repository
# ! wget https://raw.githubusercontent.com/dataprofessor/data/master/acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv

In [4]:
import pandas as pd

In [5]:
df3 = pd.read_csv('acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv')

In [6]:
df3

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL15886,CC[N+](C)(CC)CC(=O)CCN1C(=O)CCC1=O.[I-],inactive,255.338,0.5810,0.0,3.0,4.000000
1,1,CHEMBL556129,C[n+]1ccccc1CCC(O)CCl.[I-],inactive,200.689,1.0434,1.0,1.0,3.698970
2,2,CHEMBL15795,C[N+](C)(C)CCCCl.[Br-],inactive,136.646,1.3215,0.0,0.0,3.585027
3,3,CHEMBL276539,BrCCCCCC[n+]1ccccc1.[Br-],inactive,243.168,2.9294,0.0,0.0,4.221849
4,4,CHEMBL278956,CC[N+](C)(CC)CCc1ccncc1.[I-],inactive,193.314,2.1105,0.0,1.0,3.698970
...,...,...,...,...,...,...,...,...,...
1566,1566,CHEMBL5219903,CN1CCN(C(=O)Oc2ccc(/C=C/c3cc(OC(=O)N4CCN(C)CC4...,intermediate,606.724,3.0956,0.0,9.0,5.156767
1567,1567,CHEMBL5220947,O=C(Oc1ccc(/C=C/c2cc(OC(=O)N3CCN(Cc4ccccc4)CC3...,intermediate,835.018,7.8068,0.0,9.0,5.386158
1568,1568,CHEMBL5271210,O=C1[C@@H]2Cc3c([nH]c4ccccc34)[C@@H](c3ccc4c(c...,intermediate,576.697,4.8838,1.0,5.0,5.815309
1569,1569,CHEMBL5275356,COc1ccc([C@@H]2c3[nH]c4ccccc4c3C[C@H]3C(=O)N(C...,intermediate,562.714,5.1637,1.0,4.0,5.490663
1570,1570,CHEMBL5422194,CCN(CCCCCCOc1ccc(/C=C/C(=O)c2c(O)cc(OC)c(O)c2O...,active,563.691,6.4810,2.0,8.0,6.387216

In [7]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [8]:
! cat molecule.smi | head -5

CC[N+](C)(CC)CC(=O)CCN1C(=O)CCC1=O.[I-]	CHEMBL15886
C[n+]1ccccc1CCC(O)CCl.[I-]	CHEMBL556129
C[N+](C)(C)CCCCl.[Br-]	CHEMBL15795
BrCCCCCC[n+]1ccccc1.[Br-]	CHEMBL276539
CC[N+](C)(CC)CCc1ccncc1.[I-]	CHEMBL278956
cat: write error: Broken pipe

In [9]:
! cat molecule.smi | wc -l

1571

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [10]:
! cat padel.sh

java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/PubchemFingerprinter.xml -dir ./ -file descriptors_output.csv

In [15]:
! bash padel.sh

Processing CHEMBL15886 in molecule.smi (1/1571).
Processing CHEMBL556129 in molecule.smi (2/1571).
Processing CHEMBL15795 in molecule.smi (3/1571).
Processing CHEMBL276539 in molecule.smi (4/1571).
Processing CHEMBL278956 in molecule.smi (5/1571).
Processing CHEMBL539116 in molecule.smi (6/1571).
Processing CHEMBL276538 in molecule.smi (7/1571).
Processing CHEMBL15822 in molecule.smi (8/1571).
Processing CHEMBL538102 in molecule.smi (9/1571).
Processing CHEMBL1159683 in molecule.smi (10/1571).
Processing CHEMBL539117 in molecule.smi (11/1571).
Processing CHEMBL53239 in molecule.smi (12/1571).
Processing CHEMBL50735 in molecule.smi (13/1571).
Processing CHEMBL50736 in molecule.smi (14/1571).
Processing CHEMBL301958 in molecule.smi (16/1571).
Processing CHEMBL53598 in molecule.smi (15/1571).
Processing CHEMBL50462 in molecule.smi (17/1571).
Processing CHEMBL53666 in molecule.smi (18/1571).
Processing CHEMBL51934 in molecule.smi (19/1571).
Processing CHEMBL50309 in molecule.smi (20/1571).
Processing CHEMBL298896 in molecule.smi (21/1571).
Processing CHEMBL300315 in molecule.smi (22/1571).
Processing CHEMBL53978 in molecule.smi (24/1571).
Processing CHEMBL299147 in molecule.smi (23/1571).
Processing CHEMBL52967 in molecule.smi (25/1571).
Processing CHEMBL50322 in molecule.smi (26/1571).
Processing CHEMBL51168 in molecule.smi (27/1571).
Processing CHEMBL53240 in molecule.smi (28/1571).
Processing CHEMBL53973 in molecule.smi (29/1571).
Processing CHEMBL298154 in molecule.smi (30/1571).
Processing CHEMBL54086 in molecule.smi (31/1571).
Processing CHEMBL299771 in molecule.smi (32/1571).
Processing CHEMBL1794989 in molecule.smi (33/1571).
Processing CHEMBL53830 in molecule.smi (34/1571).
Processing CHEMBL53182 in molecule.smi (35/1571).
Processing CHEMBL50410 in molecule.smi (36/1571).
Processing CHEMBL52181 in molecule.smi (37/1571).
Processing CHEMBL50264 in molecule.smi (38/1571).
Processing CHEMBL54186 in molecule.smi (39/1571).
Processing CHEMBL50263 in molecule.smi (40/1571).
Processing CHEMBL52608 in molecule.smi (41/1571).
Processing CHEMBL53715 in molecule.smi (42/1571).
Processing CHEMBL51063 in molecule.smi (43/1571).
Processing CHEMBL298577 in molecule.smi (44/1571).
Processing CHEMBL50578 in molecule.smi (45/1571).
Processing CHEMBL1794987 in molecule.smi (46/1571).
Processing CHEMBL298674 in molecule.smi (47/1571).
Processing CHEMBL298685 in molecule.smi (48/1571).
Processing CHEMBL1794988 in molecule.smi (49/1571). Average speed: 5.27 s/mol.
Processing CHEMBL95 in molecule.smi (50/1571). Average speed: 3.12 s/mol.
Processing CHEMBL350442 in molecule.smi (51/1571). Average speed: 2.55 s/mol.
Processing CHEMBL23455 in molecule.smi (52/1571). Average speed: 1.92 s/mol.
Processing CHEMBL29835 in molecule.smi (53/1571). Average speed: 1.60 s/mol.
Processing CHEMBL89011 in molecule.smi (54/1571). Average speed: 1.37 s/mol.
Processing CHEMBL50608 in molecule.smi (55/1571). Average speed: 1.23 s/mol.
Processing CHEMBL60167 in molecule.smi (56/1571). Average speed: 1.11 s/mol.
Processing CHEMBL89012 in molecule.smi (57/1571). Average speed: 1.01 s/mol.
Processing CHEMBL314800 in molecule.smi (58/1571). Average speed: 0.93 s/mol.
Processing CHEMBL422685 in molecule.smi (59/1571). Average speed: 1.07 s/mol.
Processing CHEMBL100334 in molecule.smi (60/1571). Average speed: 0.99 s/mol.
Processing CHEMBL153912 in molecule.smi (61/1571). Average speed: 0.96 s/mol.
Processing CHEMBL155244 in molecule.smi (62/1571). Average speed: 0.89 s/mol.
Processing CHEMBL100819 in molecule.smi (63/1571). Average speed: 0.85 s/mol.
Processing CHEMBL323618 in molecule.smi (64/1571). Average speed: 0.81 s/mol.
Processing CHEMBL347398 in molecule.smi (65/1571). Average speed: 0.76 s/mol.
Processing CHEMBL98497 in molecule.smi (66/1571). Average speed: 0.72 s/mol.
Processing CHEMBL431058 in molecule.smi (67/1571). Average speed: 0.69 s/mol.
Processing CHEMBL154894 in molecule.smi (68/1571). Average speed: 0.66 s/mol.
Processing CHEMBL100510 in molecule.smi (69/1571). Average speed: 0.64 s/mol.
Processing CHEMBL99605 in molecule.smi (70/1571). Average speed: 0.62 s/mol.
Processing CHEMBL347885 in molecule.smi (71/1571). Average speed: 0.65 s/mol.
Processing CHEMBL345798 in molecule.smi (72/1571). Average speed: 0.62 s/mol.
Processing CHEMBL502 in molecule.smi (73/1571). Average speed: 0.60 s/mol.
Processing CHEMBL154893 in molecule.smi (74/1571). Average speed: 0.60 s/mol.
Processing CHEMBL152279 in molecule.smi (75/1571). Average speed: 0.59 s/mol.
Processing CHEMBL420827 in molecule.smi (76/1571). Average speed: 0.58 s/mol.
Processing CHEMBL100718 in molecule.smi (77/1571). Average speed: 0.57 s/mol.
Processing CHEMBL100020 in molecule.smi (78/1571). Average speed: 0.55 s/mol.
Processing CHEMBL101028 in molecule.smi (79/1571). Average speed: 0.54 s/mol.
Processing CHEMBL102142 in molecule.smi (80/1571). Average speed: 0.53 s/mol.
Processing CHEMBL99606 in molecule.smi (81/1571). Average speed: 0.52 s/mol.
Processing CHEMBL156882 in molecule.smi (82/1571). Average speed: 0.51 s/mol.
Processing CHEMBL94 in molecule.smi (83/1571). Average speed: 0.49 s/mol.
Processing CHEMBL101518 in molecule.smi (84/1571). Average speed: 0.48 s/mol.
Processing CHEMBL156957 in molecule.smi (85/1571). Average speed: 0.47 s/mol.
Processing CHEMBL101988 in molecule.smi (87/1571). Average speed: 0.46 s/mol.
Processing CHEMBL430679 in molecule.smi (86/1571). Average speed: 0.46 s/mol.
Processing CHEMBL329518 in molecule.smi (89/1571). Average speed: 0.44 s/mol.
Processing CHEMBL154026 in molecule.smi (88/1571). Average speed: 0.44 s/mol.
Processing CHEMBL329733 in molecule.smi (90/1571). Average speed: 0.43 s/mol.
Processing CHEMBL659 in molecule.smi (91/1571). Average speed: 0.42 s/mol.
Processing CHEMBL101155 in molecule.smi (92/1571). Average speed: 0.41 s/mol.
Processing CHEMBL421820 in molecule.smi (93/1571). Average speed: 0.41 s/mol.
Processing CHEMBL101940 in molecule.smi (94/1571). Average speed: 0.41 s/mol.
Processing CHEMBL101809 in molecule.smi (95/1571). Average speed: 0.40 s/mol.
Processing CHEMBL436226 in molecule.smi (96/1571). Average speed: 0.40 s/mol.
Processing CHEMBL317541 in molecule.smi (97/1571). Average speed: 0.40 s/mol.
Processing CHEMBL117521 in molecule.smi (98/1571). Average speed: 0.40 s/mol.
Processing CHEMBL19470 in molecule.smi (99/1571). Average speed: 0.40 s/mol.
Processing CHEMBL18863 in molecule.smi (100/1571). Average speed: 0.41 s/mol.
Processing CHEMBL278742 in molecule.smi (101/1571). Average speed: 0.43 s/mol.
Processing CHEMBL282920 in molecule.smi (102/1571). Average speed: 0.43 s/mol.
Processing CHEMBL19486 in molecule.smi (103/1571). Average speed: 0.42 s/mol.
Processing CHEMBL538103 in molecule.smi (104/1571). Average speed: 0.43 s/mol.
Processing CHEMBL19337 in molecule.smi (105/1571). Average speed: 0.43 s/mol.
Processing CHEMBL279153 in molecule.smi (106/1571). Average speed: 0.44 s/mol.
Processing CHEMBL278327 in molecule.smi (107/1571). Average speed: 0.44 s/mol.
Processing CHEMBL278309 in molecule.smi (109/1571). Average speed: 0.43 s/mol.
Processing CHEMBL279876 in molecule.smi (108/1571). Average speed: 0.43 s/mol.
Processing CHEMBL18903 in molecule.smi (110/1571). Average speed: 0.42 s/mol.
Processing CHEMBL19487 in molecule.smi (111/1571). Average speed: 0.42 s/mol.
Processing CHEMBL19388 in molecule.smi (112/1571). Average speed: 0.41 s/mol.
Processing CHEMBL283112 in molecule.smi (113/1571). Average speed: 0.43 s/mol.
Processing CHEMBL19318 in molecule.smi (114/1571). Average speed: 0.43 s/mol.
Processing CHEMBL282917 in molecule.smi (115/1571). Average speed: 0.44 s/mol.
Processing CHEMBL18766 in molecule.smi (116/1571). Average speed: 0.43 s/mol.
Processing CHEMBL18920 in molecule.smi (117/1571). Average speed: 0.44 s/mol.
Processing CHEMBL19325 in molecule.smi (118/1571). Average speed: 0.44 s/mol.
Processing CHEMBL428683 in molecule.smi (119/1571). Average speed: 0.43 s/mol.
Processing CHEMBL18432 in molecule.smi (120/1571). Average speed: 0.43 s/mol.
Processing CHEMBL19537 in molecule.smi (121/1571). Average speed: 0.43 s/mol.
Processing CHEMBL552981 in molecule.smi (122/1571). Average speed: 0.42 s/mol.
Processing CHEMBL395280 in molecule.smi (123/1571). Average speed: 0.42 s/mol.
Processing CHEMBL45154 in molecule.smi (124/1571). Average speed: 0.42 s/mol.
Processing CHEMBL161248 in molecule.smi (125/1571). Average speed: 0.42 s/mol.
Processing CHEMBL159878 in molecule.smi (126/1571). Average speed: 0.41 s/mol.
Processing CHEMBL350644 in molecule.smi (127/1571). Average speed: 0.41 s/mol.
Processing CHEMBL161062 in molecule.smi (128/1571). Average speed: 0.40 s/mol.
Processing CHEMBL160088 in molecule.smi (129/1571). Average speed: 0.39 s/mol.
Processing CHEMBL347813 in molecule.smi (130/1571). Average speed: 0.39 s/mol.
Processing CHEMBL159800 in molecule.smi (131/1571). Average speed: 0.39 s/mol.
Processing CHEMBL159701 in molecule.smi (132/1571). Average speed: 0.38 s/mol.
Processing CHEMBL159576 in molecule.smi (133/1571). Average speed: 0.38 s/mol.
Processing CHEMBL159401 in molecule.smi (134/1571). Average speed: 0.38 s/mol.
Processing CHEMBL159351 in molecule.smi (136/1571). Average speed: 0.38 s/mol.
Processing CHEMBL161003 in molecule.smi (135/1571). Average speed: 0.38 s/mol.
Processing CHEMBL161149 in molecule.smi (137/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161179 in molecule.smi (138/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161199 in molecule.smi (139/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159474 in molecule.smi (140/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161100 in molecule.smi (141/1571). Average speed: 0.37 s/mol.
Processing CHEMBL160009 in molecule.smi (142/1571). Average speed: 0.37 s/mol.
Processing CHEMBL162747 in molecule.smi (143/1571). Average speed: 0.37 s/mol.
Processing CHEMBL160095 in molecule.smi (144/1571). Average speed: 0.37 s/mol.
Processing CHEMBL353129 in molecule.smi (145/1571). Average speed: 0.36 s/mol.
Processing CHEMBL158860 in molecule.smi (146/1571). Average speed: 0.36 s/mol.
Processing CHEMBL159353 in molecule.smi (147/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159702 in molecule.smi (148/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161274 in molecule.smi (149/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159813 in molecule.smi (150/1571). Average speed: 0.37 s/mol.
Processing CHEMBL349043 in molecule.smi (151/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159704 in molecule.smi (152/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159454 in molecule.smi (153/1571). Average speed: 0.38 s/mol.
Processing CHEMBL161795 in molecule.smi (154/1571). Average speed: 0.38 s/mol.
Processing CHEMBL351536 in molecule.smi (155/1571). Average speed: 0.37 s/mol.
Processing CHEMBL423777 in molecule.smi (156/1571). Average speed: 0.37 s/mol.
Processing CHEMBL158637 in molecule.smi (157/1571). Average speed: 0.37 s/mol.
Processing CHEMBL349694 in molecule.smi (158/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161607 in molecule.smi (159/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159634 in molecule.smi (160/1571). Average speed: 0.37 s/mol.
Processing CHEMBL162750 in molecule.smi (161/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161139 in molecule.smi (162/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161190 in molecule.smi (163/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159553 in molecule.smi (164/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161269 in molecule.smi (165/1571). Average speed: 0.37 s/mol.
Processing CHEMBL161779 in molecule.smi (166/1571). Average speed: 0.37 s/mol.
Processing CHEMBL160008 in molecule.smi (167/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159779 in molecule.smi (168/1571). Average speed: 0.37 s/mol.
Processing CHEMBL440547 in molecule.smi (169/1571). Average speed: 0.37 s/mol.
Processing CHEMBL159333 in molecule.smi (170/1571). Average speed: 0.37 s/mol.
Processing CHEMBL557161 in molecule.smi (171/1571). Average speed: 0.37 s/mol.
Processing CHEMBL423639 in molecule.smi (172/1571). Average speed: 0.37 s/mol.
Processing CHEMBL542287 in molecule.smi (173/1571). Average speed: 0.37 s/mol.
Processing CHEMBL553467 in molecule.smi (174/1571). Average speed: 0.37 s/mol.
Processing CHEMBL536467 in molecule.smi (175/1571). Average speed: 0.37 s/mol.
Processing CHEMBL538556 in molecule.smi (176/1571). Average speed: 0.37 s/mol.
Processing CHEMBL542771 in molecule.smi (177/1571). Average speed: 0.37 s/mol.
Processing CHEMBL544887 in molecule.smi (178/1571). Average speed: 0.37 s/mol.
Processing CHEMBL351412 in molecule.smi (179/1571). Average speed: 0.37 s/mol.
Processing CHEMBL538098 in molecule.smi (180/1571). Average speed: 0.37 s/mol.
Processing CHEMBL540602 in molecule.smi (181/1571). Average speed: 0.37 s/mol.
Processing CHEMBL351647 in molecule.smi (182/1571). Average speed: 0.36 s/mol.
Processing CHEMBL536932 in molecule.smi (183/1571). Average speed: 0.36 s/mol.
Processing CHEMBL163508 in molecule.smi (184/1571). Average speed: 0.36 s/mol.
Processing CHEMBL349073 in molecule.smi (185/1571). Average speed: 0.36 s/mol.
Processing CHEMBL541356 in molecule.smi (186/1571). Average speed: 0.36 s/mol.
Processing CHEMBL164797 in molecule.smi (187/1571). Average speed: 0.36 s/mol.
Processing CHEMBL541853 in molecule.smi (188/1571). Average speed: 0.36 s/mol.
Processing CHEMBL542477 in molecule.smi (189/1571). Average speed: 0.36 s/mol.
Processing CHEMBL545539 in molecule.smi (190/1571). Average speed: 0.36 s/mol.
Processing CHEMBL545774 in molecule.smi (191/1571). Average speed: 0.36 s/mol.
Processing CHEMBL540830 in molecule.smi (192/1571). Average speed: 0.36 s/mol.
Processing CHEMBL544369 in molecule.smi (193/1571). Average speed: 0.36 s/mol.
Processing CHEMBL542732 in molecule.smi (194/1571). Average speed: 0.36 s/mol.
Processing CHEMBL544603 in molecule.smi (195/1571). Average speed: 0.36 s/mol.
Processing CHEMBL544143 in molecule.smi (196/1571). Average speed: 0.36 s/mol.
Processing CHEMBL542236 in molecule.smi (197/1571). Average speed: 0.36 s/mol.
Processing CHEMBL1677 in molecule.smi (198/1571). Average speed: 0.36 s/mol.
Processing CHEMBL557225 in molecule.smi (199/1571). Average speed: 0.36 s/mol.
Processing CHEMBL542482 in molecule.smi (200/1571). Average speed: 0.36 s/mol.
Processing CHEMBL284348 in molecule.smi (201/1571). Average speed: 0.36 s/mol.
Processing CHEMBL543906 in molecule.smi (202/1571). Average speed: 0.35 s/mol.
Processing CHEMBL542234 in molecule.smi (203/1571). Average speed: 0.35 s/mol.
Processing CHEMBL58146 in molecule.smi (204/1571). Average speed: 0.35 s/mol.
Processing CHEMBL543667 in molecule.smi (205/1571). Average speed: 0.35 s/mol.
Processing CHEMBL555320 in molecule.smi (206/1571). Average speed: 0.35 s/mol.
Processing CHEMBL539811 in molecule.smi (207/1571). Average speed: 0.36 s/mol.
Processing CHEMBL538533 in molecule.smi (208/1571). Average speed: 0.36 s/mol.
Processing CHEMBL540837 in molecule.smi (209/1571). Average speed: 0.35 s/mol.
Processing CHEMBL544605 in molecule.smi (210/1571). Average speed: 0.35 s/mol.
Processing CHEMBL347914 in molecule.smi (211/1571). Average speed: 0.35 s/mol.
Processing CHEMBL346142 in molecule.smi (212/1571). Average speed: 0.35 s/mol.
Processing CHEMBL154735 in molecule.smi (213/1571). Average speed: 0.35 s/mol.
Processing CHEMBL155109 in molecule.smi (214/1571). Average speed: 0.35 s/mol.
Processing CHEMBL348034 in molecule.smi (215/1571). Average speed: 0.35 s/mol.
Processing CHEMBL154488 in molecule.smi (216/1571). Average speed: 0.35 s/mol.
Processing CHEMBL157902 in molecule.smi (217/1571). Average speed: 0.35 s/mol.
Processing CHEMBL345251 in molecule.smi (218/1571). Average speed: 0.35 s/mol.
Processing CHEMBL152842 in molecule.smi (219/1571). Average speed: 0.35 s/mol.
Processing CHEMBL154228 in molecule.smi (220/1571). Average speed: 0.35 s/mol.
Processing CHEMBL345439 in molecule.smi (221/1571). Average speed: 0.34 s/mol.
Processing CHEMBL348865 in molecule.smi (222/1571). Average speed: 0.34 s/mol.
Processing CHEMBL351760 in molecule.smi (223/1571). Average speed: 0.34 s/mol.
Processing CHEMBL154541 in molecule.smi (224/1571). Average speed: 0.34 s/mol.
Processing CHEMBL152362 in molecule.smi (225/1571). Average speed: 0.34 s/mol.
Processing CHEMBL347666 in molecule.smi (226/1571). Average speed: 0.34 s/mol.
Processing CHEMBL154257 in molecule.smi (227/1571). Average speed: 0.34 s/mol.
Processing CHEMBL153847 in molecule.smi (228/1571). Average speed: 0.34 s/mol.
Processing CHEMBL154319 in molecule.smi (229/1571). Average speed: 0.34 s/mol.
Processing CHEMBL348716 in molecule.smi (230/1571). Average speed: 0.34 s/mol.
Processing CHEMBL435034 in molecule.smi (231/1571). Average speed: 0.34 s/mol.
Processing CHEMBL155359 in molecule.smi (232/1571). Average speed: 0.34 s/mol.
Processing CHEMBL154945 in molecule.smi (233/1571). Average speed: 0.34 s/mol.
Processing CHEMBL155603 in molecule.smi (234/1571). Average speed: 0.34 s/mol.
Processing CHEMBL350692 in molecule.smi (235/1571). Average speed: 0.35 s/mol.
Processing CHEMBL155460 in molecule.smi (236/1571). Average speed: 0.35 s/mol.
Processing CHEMBL356922 in molecule.smi (237/1571). Average speed: 0.35 s/mol.
Processing CHEMBL157971 in molecule.smi (238/1571). Average speed: 0.35 s/mol.
Processing CHEMBL357553 in molecule.smi (239/1571). Average speed: 0.35 s/mol.
Processing CHEMBL347336 in molecule.smi (240/1571). Average speed: 0.35 s/mol.
Processing CHEMBL155211 in molecule.smi (241/1571). Average speed: 0.35 s/mol.
Processing CHEMBL154297 in molecule.smi (242/1571). Average speed: 0.35 s/mol.
Processing CHEMBL345442 in molecule.smi (243/1571). Average speed: 0.35 s/mol.
Processing CHEMBL42531 in molecule.smi (245/1571). Average speed: 0.35 s/mol.
Processing CHEMBL345607 in molecule.smi (244/1571). Average speed: 0.35 s/mol.
Processing CHEMBL433041 in molecule.smi (246/1571). Average speed: 0.34 s/mol.
Processing CHEMBL290628 in molecule.smi (247/1571). Average speed: 0.34 s/mol.
Processing CHEMBL44080 in molecule.smi (248/1571). Average speed: 0.34 s/mol.
Processing CHEMBL42667 in molecule.smi (249/1571). Average speed: 0.34 s/mol.
Processing CHEMBL295462 in molecule.smi (250/1571). Average speed: 0.34 s/mol.
Processing CHEMBL156290 in molecule.smi (251/1571). Average speed: 0.34 s/mol.
Processing CHEMBL154211 in molecule.smi (252/1571). Average speed: 0.34 s/mol.
Processing CHEMBL160914 in molecule.smi (253/1571). Average speed: 0.34 s/mol.
Processing CHEMBL155300 in molecule.smi (254/1571). Average speed: 0.34 s/mol.
Processing CHEMBL160913 in molecule.smi (255/1571). Average speed: 0.33 s/mol.
Processing CHEMBL155983 in molecule.smi (256/1571). Average speed: 0.33 s/mol.
Processing CHEMBL345638 in molecule.smi (257/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96643 in molecule.smi (258/1571). Average speed: 0.33 s/mol.
Processing CHEMBL329526 in molecule.smi (259/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96542 in molecule.smi (260/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96861 in molecule.smi (261/1571). Average speed: 0.33 s/mol.
Processing CHEMBL76173 in molecule.smi (262/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96889 in molecule.smi (263/1571). Average speed: 0.33 s/mol.
Processing CHEMBL421501 in molecule.smi (264/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96588 in molecule.smi (265/1571). Average speed: 0.33 s/mol.
Processing CHEMBL328904 in molecule.smi (266/1571). Average speed: 0.33 s/mol.
Processing CHEMBL92563 in molecule.smi (267/1571). Average speed: 0.33 s/mol.
Processing CHEMBL76014 in molecule.smi (268/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96406 in molecule.smi (269/1571). Average speed: 0.33 s/mol.
Processing CHEMBL330188 in molecule.smi (270/1571). Average speed: 0.33 s/mol.
Processing CHEMBL96196 in molecule.smi (271/1571). Average speed: 0.33 s/mol.

In [16]:
! ls -l

total 46484
-rw-r--r-- 1 mcubi students  1013813 Mar 23 18:29 acetylcholinesterase_01_bioactivity_data_raw.csv
-rw-r--r-- 1 mcubi students   113254 Mar 23 18:29 acetylcholinesterase_02_bioactivity_data_preprocessed.csv
-rw-r--r-- 1 mcubi students   127407 Mar 23 18:29 acetylcholinesterase_03_bioactivity_data_curated.csv
-rw-r--r-- 1 mcubi students   218232 Apr  2 12:10 acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv
-rw-r--r-- 1 mcubi students   163057 Apr  2 12:12 acetylcholinesterase_05_bioactivity_data_2class_pIC50.csv
-rw-r--r-- 1 mcubi students  8363909 Mar 23 18:14 acetylcholinesterase_06_bioactivity_data_3class_pIC50_pubchem_fp.csv
-rw-r--r-- 1 mcubi students  6323895 Mar 23 18:14 acetylcholinesterase_07_bioactivity_data_2class_pIC50_pubchem_fp.csv
-rw-r--r-- 1 mcubi students   134859 Mar 23 18:32 acetylcholinesterase.zip
-rw-r--r-- 1 mcubi students   105848 Apr  2 11:58 CDD_ML_Part_1_Acetylcholinesterase_Bioactivity_Data_Concised.ipynb
-rw-r--r-- 1 mcubi students   395301 Apr  2 12:23 CDD_ML_Part_2_Acetylcholinesterase_Exploratory_Data_Analysis.ipynb
-rw-r--r-- 1 mcubi students   272967 Apr  2 13:52 CDD_ML_Part_3_Acetylcholinesterase_Descriptor_Dataset_Preparation.ipynb
-rw-r--r-- 1 mcubi students   100076 Mar 23 18:14 CDD_ML_Part_4_Acetylcholinesterase_Regression_Random_Forest.ipynb
-rw-r--r-- 1 mcubi students   230778 Mar 23 18:14 CDD_ML_Part_5_Acetylcholinesterase_Compare_Regressors.ipynb
-rw-r--r-- 1 mcubi students  2803612 Apr  2 13:51 descriptors_output.csv
drwxr-xr-x 3 mcubi students       68 Apr  2 13:26 __MACOSX
-rw-r--r-- 1 mcubi students      125 Apr  2 12:22 mannwhitneyu_LogP.csv
-rw-r--r-- 1 mcubi students      123 Apr  2 12:21 mannwhitneyu_MW.csv
-rw-r--r-- 1 mcubi students      133 Apr  2 12:22 mannwhitneyu_NumHAcceptors.csv
-rw-r--r-- 1 mcubi students      129 Apr  2 12:22 mannwhitneyu_NumHDonors.csv
-rw-r--r-- 1 mcubi students      126 Apr  2 12:21 mannwhitneyu_pIC50.csv
-rw-r--r-- 1 mcubi students   102758 Apr  2 13:27 molecule.smi
drwxrwxr-x 4 mcubi students     4096 May 30  2020 PaDEL-Descriptor
-rw-r--r-- 1 mcubi students      231 Apr  2 12:56 padel.sh
-rw-r--r-- 1 mcubi students 25768637 Apr  2 12:56 padel.zip
-rw-r--r-- 1 mcubi students    14584 Apr  2 12:14 plot_bioactivity_class.pdf
-rw-r--r-- 1 mcubi students    15536 Apr  2 12:16 plot_ic50.pdf
-rw-r--r-- 1 mcubi students    14411 Apr  2 12:21 plot_LogP.pdf
-rw-r--r-- 1 mcubi students    14769 Apr  2 12:21 plot_MW.pdf
-rw-r--r-- 1 mcubi students   220014 Apr  2 12:15 plot_MW_vs_LogP.pdf
-rw-r--r-- 1 mcubi students    15175 Apr  2 12:22 plot_NumHAcceptors.pdf
-rw-r--r-- 1 mcubi students    14396 Apr  2 12:22 plot_NumHDonors.pdf
-rw-r--r-- 1 mcubi students       29 Mar 23 18:14 README.md
-rw-r--r-- 1 mcubi students   976364 Apr  2 12:23 results.zip

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [17]:
df3_X = pd.read_csv('descriptors_output.csv')

In [18]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL15795,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL276538,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL276539,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL556129,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL278956,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,CHEMBL5092574,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1567,CHEMBL5219903,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1568,CHEMBL5271210,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1569,CHEMBL5275356,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1570,CHEMBL5220947,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1567,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1568,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1569,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1570,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [20]:
df3_Y = df3['pIC50']
df3_Y

0       4.000000
1       3.698970
2       3.585027
3       4.221849
4       3.698970
          ...
1566    5.156767
1567    5.386158
1568    5.815309
1569    5.490663
1570    6.387216
Name: pIC50, Length: 1571, dtype: float64

## **Combining X and Y variable**

In [21]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.000000
1,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,3.698970
2,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,3.585027
3,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.221849
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,3.698970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1566,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.156767
1567,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.386158
1568,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.815309
1569,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.490663
1570,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.387216

In [22]:
dataset3.to_csv('acetylcholinesterase_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**